-- CREATE TABLE customer
CREATE TABLE IF NOT EXISTS customer(
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
email VARCHAR(60) NOT NULL,
company VARCHAR(60) NULL,
street VARCHAR(50) NOT NULL,
city VARCHAR(40) NOT NULL,
state CHAR(2) NOT NULL DEFAULT 'PA',
zip SMALLINT NOT NULL,
phone VARCHAR(20) NOT NULL,
birth_date DATE NULL,
sex CHAR(1) NOT NULL,
date_entered TIMESTAMP NOT NULL,
id SERIAL PRIMARY KEY
);

CREATE TYPE sex_type AS ENUM ('M', 'F', 'O');
-- DROP TYPE
-- DROP TYPE sex_type;
-- Change COLUMN TYPE
ALTER TABLE customer
ALTER COLUMN sex
TYPE sex_type USING sex::sex_type;
-- CREATE TABLE sales_person
CREATE TABLE IF NOT EXISTS sales_person(
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
email VARCHAR(60) NOT NULL,
street VARCHAR(50) NOT NULL,
city VARCHAR(40) NOT NULL,
state CHAR(2) NOT NULL DEFAULT 'PA',
zip SMALLINT NOT NULL,
phone VARCHAR(20) NOT NULL,
birth_date DATE NULL,
sex sex_type NOT NULL,
date_hired TIMESTAMP NOT NULL,
id SERIAL PRIMARY KEY
);
-- CREATE TABLE product_type
CREATE TABLE IF NOT EXISTS product_type(
name VARCHAR(30) NOT NULL,
id SERIAL PRIMARY KEY);
-- CREATE TABLE product
CREATE TABLE IF NOT EXISTS product(
type_id INTEGER REFERENCES product_type(id),
name VARCHAR(30) NOT NULL,
supplier VARCHAR(30) NOT NULL,
description TEXT NOT NULL,
id SERIAL PRIMARY KEY);